        !COMPILER-GENERATED INTERFACE MODULE: Fri Jan 15 14:42:44 2016
        MODULE DLAMCH__genmod
          INTERFACE 
            FUNCTION DLAMCH(CMACH)
              CHARACTER(LEN=1) :: CMACH
              REAL(KIND=8) :: DLAMCH
            END FUNCTION DLAMCH
          END INTERFACE 
        END MODULE DLAMCH__genmod
