        !COMPILER-GENERATED INTERFACE MODULE: Fri Jan 15 14:42:44 2016
        MODULE DLAMC4__genmod
          INTERFACE 
            SUBROUTINE DLAMC4(EMIN,START,BASE)
              INTEGER(KIND=4) :: EMIN
              REAL(KIND=8) :: START
              INTEGER(KIND=4) :: BASE
            END SUBROUTINE DLAMC4
          END INTERFACE 
        END MODULE DLAMC4__genmod
